version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
      time: "07:30"
    commit-message:
      prefix: "#26 - (php) "
    target-branch: main
    open-pull-requests-limit: 1
