version: '3'

services:

  php:
    build:
      context: environment/dev/php
      args:
        INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
    ports:
      - ${EXTERNAL_PHP_PORT}:8000
    container_name: meetup-php
    working_dir: /application
    user: ${CURRENT_UID:-1000}
    entrypoint: environment/dev/php/bin/entrypoint.sh
    volumes:
      -  ./tests/manual/public:/application/public
      - .:/application
      - ./environment/dev/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - meetup-dev
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  redis:
    image: 'redis:6'
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./storage/redis:/data
    networks:
      - meetup-dev
  node:
    image: "node:14"
    tty: true
    ports:
      -  ${NODE_PORT}:3000
    working_dir: /src
    volumes:
      - ./:/src
    networks:
      - meetup-dev
networks:
  meetup-dev:
    driver: bridge
