version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./:/var/www
      - ./environment/dev/nginx/nginx.conf:/etc/nginx/conf.d/app.conf
    ports:
      - 80:80
    networks:
      - meetup-dev
  php:
    build:
      context: ./environment/dev/php
    working_dir: /var/www
    environment:
      - DOCKER=1
    volumes:
      - .:/var/www
      - ./environment/dev/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 9000:9000
    networks:
      - meetup-dev
    depends_on:
      - db

  db:
    image: 'postgres:13'
    ports:
      - 5432:5432
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - meetup-dev
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:6'
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis:/data
    networks:
      - meetup-dev

networks:
  meetup-dev:
    driver: bridge